import type { SlugDef } from './roofingSlugs1';

export const SLUGS_3: SlugDef[] = [
  {
    slug: 'free-skillion-roof-calculator',
    defaultTab: 'roof-area',
    name: 'Skillion Roof Calculator',
    mTitle: 'Free Skillion Roof Calculator - Area, Rafter & Materials | QuoteCore+',
    mDesc: 'Free skillion roof calculator. Calculate skillion (mono-pitch) roof area, rafter length, and materials. No signup required.',
    ogTitle: 'Free Skillion Roof Calculator - Area & Rafters',
    ogDesc: 'Free skillion roof calculator. Area, rafters, and materials.',
    h1: 'Skillion Roof Calculator',
    hero: 'Calculate skillion (mono-pitch/shed) roof area, rafter length, and material quantities from span and pitch. Single-slope calculations with waste. Free, no signup.',
    tipsH: 'Skillion roofs - did you know?',
    tips: [
      ['What is a skillion roof?', 'A skillion (mono-pitch or shed roof) has a single slope. It is the simplest roof form - one rafter length, one slope, no ridge. Common on extensions, modern homes, and agricultural buildings.'],
      ['Skillion rafter calculation', 'Only one rafter length: rafter = span ÷ cos(pitch°). At 35° with 5m span: 5 ÷ cos(35) = 6.10m. Add overhang separately. No ridge, no hips, no valleys - simplest rafter calc in roofing.'],
      ['Typical skillion pitches', 'Skillion roofs are often steeper than flat roofs but shallower than gable roofs: 10°-25° is common. Modern architecture favours low-pitch skillions (5°-15°) with metal roofing. Minimum pitch depends on material.'],
      ['Drainage on skillion roofs', 'Water runs off one side only. Ensure the low side has adequate gutter capacity. At 15° pitch, a skillion sheds water almost as fast as a 15° gable - but ALL water goes to one side. Size gutters accordingly.'],
    ],
    formulas: [
      ['Roof area', 'area = span × length × (1 ÷ cos(pitch°))'],
      ['Rafter length', 'rafter = span ÷ cos(pitch°)'],
      ['Material quantity', 'qty = area × (1 + waste%) ÷ coverage'],
      ['Water runoff (single side)', 'runoff = area × rainfall_intensity'],
    ],
    faqs: [
      ['How do I calculate skillion roof area?', 'span × length × (1 ÷ cos(pitch°)). At 15°, 5m span, 10m length: 5 × 10 × 1.035 = 51.8 m².'],
      ['What pitch for a skillion roof?', 'Typically 10°-25°. Modern homes: 5°-15° with metal roofing. Minimum depends on material - check manufacturer specs.'],
      ['How is a skillion different from a gable?', 'Skillion = single slope (one rafter length, no ridge). Gable = two slopes meeting at ridge. Skillion is simpler but sheds all water to one side.'],
      ['Best free skillion roof calculator?', 'One that handles single-slope area, rafter length, and materials. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-squares-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Squares Calculator',
    mTitle: 'Free Roof Squares Calculator - Convert Area to Squares | QuoteCore+',
    mDesc: 'Free roof squares calculator. Convert roof area to roofing squares (1 square = 100 sq ft). Includes waste and bundles. No signup required.',
    ogTitle: 'Free Roof Squares Calculator - Area to Squares',
    ogDesc: 'Free roof squares calculator. Convert area to roofing squares.',
    h1: 'Roof Squares Calculator',
    hero: 'Convert roof area to roofing squares (1 square = 100 sq ft). Calculate squares, bundles, and nail quantities with waste. Imperial-first with metric conversion. Free, no signup.',
    tipsH: 'Roofing squares - did you know?',
    tips: [
      ['What is a roofing square?', 'A roofing square is 100 square feet of roof area. It is the standard unit for ordering shingles and estimating US roofing jobs. 1 square = 100 sq ft = 9.29 m². To convert m² to squares: divide by 9.29.'],
      ['Squares to bundles', 'Most architectural shingles: 3 bundles per square. 3-tab: 3-4 bundles per square. Premium/luxury: 4-5 bundles. Always check the bundle label - coverage varies by manufacturer.'],
      ['Calculating squares from plan', 'First get actual roof area: plan_area × pitch_factor. Then convert to squares: area_sqft ÷ 100. At 1,500 sq ft plan, 6:12 pitch (factor 1.118): 1,500 × 1.118 = 1,677 sq ft = 16.77 → 17 squares.'],
      ['Waste in squares', 'Add 10-15% waste to squares before ordering. 17 squares at 12% waste: 17 × 1.12 = 19.04 → 20 squares → 60 bundles. Round up - partial squares are still charged full price.'],
    ],
    formulas: [
      ['Squares from area', 'squares = ceil(roof_area_sqft ÷ 100)'],
      ['Squares with waste', 'total = ceil(squares × (1 + waste%))'],
      ['Bundles', 'bundles = total_squares × bundles_per_square'],
      ['m² to squares', 'squares = m² ÷ 9.29'],
    ],
    faqs: [
      ['What is a roofing square?', '100 sq ft of roof area. Standard US roofing unit. 1 square = 100 sq ft = 9.29 m².'],
      ['How many bundles per square?', 'Most architectural shingles: 3 bundles. 3-tab: 3-4. Premium: 4-5. Check packaging.'],
      ['How do I convert m² to squares?', 'Divide by 9.29. 100 m² = 10.77 squares. Round up to 11.'],
      ['Best free roof squares calculator?', 'One that converts area to squares, adds waste, and calculates bundles. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-square-metre-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Square Metre Calculator',
    mTitle: 'Free Roof Square Metre Calculator - m² from Dimensions | QuoteCore+',
    mDesc: 'Free roof square metre calculator. Calculate roof area in m² from dimensions and pitch. Includes waste and tile quantities. No signup required.',
    ogTitle: 'Free Roof Square Metre Calculator - m²',
    ogDesc: 'Free roof m² calculator. Area from dimensions and pitch.',
    h1: 'Roof Square Metre Calculator',
    hero: 'Calculate roof area in square metres from dimensions and pitch. Enter plan area and pitch for actual roof surface area in m², with waste and material quantities. Free, no signup.',
    tipsH: 'Roof m² - did you know?',
    tips: [
      ['Plan m² vs roof m²', 'Plan area is the footprint. Roof area is the sloped surface. At 35°, 100 m² plan = 122.1 m² roof. The pitch factor (1 ÷ cos(pitch°)) converts between them.'],
      ['m² to tiles', 'Tiles needed = m² × tiles_per_m² × (1 + waste%). Concrete: 9-12/m². Clay: 10-15/m². Plain: 60/m². Slate: 20/m². Always check manufacturer coverage.'],
      ['m² to squares (US)', '1 m² = 10.764 sq ft = 0.1076 squares. 100 m² = 10.76 squares → 11 squares (round up). Useful when working with US material specs on metric projects.'],
      ['Ordering by m²', 'Suppliers sell roofing by m² coverage. But actual coverage accounts for laps: concrete tile at 10/m² nominal might need 11/m² ordered (10% lap loss). Check "nominal" vs "effective" coverage.'],
    ],
    formulas: [
      ['Roof area (m²)', 'area = plan_m² × (1 ÷ cos(pitch°))'],
      ['Tiles from m²', 'tiles = m² × tiles_per_m² × (1 + waste%)'],
      ['m² to squares', 'squares = m² ÷ 9.29'],
      ['m² to sq ft', 'sqft = m² × 10.764'],
    ],
    faqs: [
      ['How do I calculate roof area in m²?', 'plan_m² × (1 ÷ cos(pitch°)). 100 m² plan at 35° = 100 × 1.221 = 122.1 m² roof.'],
      ['How many tiles per m²?', 'Concrete: 9-12. Clay: 10-15. Plain: 60. Slate (500mm): 20. Check manufacturer specs.'],
      ['How many m² is one square?', '1 square = 100 sq ft = 9.29 m². To convert m² to squares: m² ÷ 9.29.'],
      ['Best free roof m² calculator?', 'One that calculates from plan + pitch, converts to tiles/squares, and adds waste. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-square-footage-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Square Footage Calculator',
    mTitle: 'Free Roof Square Footage Calculator - sq ft from Dimensions | QuoteCore+',
    mDesc: 'Free roof square footage calculator. Calculate roof area in sq ft from house dimensions and pitch. Includes waste and squares. No signup required.',
    ogTitle: 'Free Roof Square Footage Calculator - sq ft',
    ogDesc: 'Free roof sq ft calculator. Area from dimensions and pitch.',
    h1: 'Roof Square Footage Calculator',
    hero: 'Calculate roof square footage from house dimensions and pitch. Enter footprint and pitch for actual roof area in sq ft, with waste and squares conversion. Free, no signup.',
    tipsH: 'Roof sq ft - did you know?',
    tips: [
      ['House sq ft vs roof sq ft', 'House footprint (floor area) is NOT roof area. At 6:12 pitch, roof area is 11.8% more than footprint. 2,000 sq ft house at 6:12 = 2,236 sq ft roof. Always calculate from footprint + pitch.'],
      ['Sq ft to squares', '1 square = 100 sq ft. Divide roof sq ft by 100. 2,236 sq ft = 22.36 → 23 squares. Add 10-15% waste: 23 × 1.12 = 25.76 → 26 squares.'],
      ['Calculating for multi-slope roofs', 'Calculate each slope separately: rectangle area × pitch factor. Add all slopes. For hip roofs, add ~4% for hip-end slopes. Subtract chimney/skylight openings (measure their sloped area, not plan area).'],
      ['Why roofers measure in squares not sq ft', 'Squares simplify ordering: shingles sold by the square, underlayment by the square, nails by square coverage. "26 squares" is easier to communicate than "2,576 sq ft including waste."'],
    ],
    formulas: [
      ['Roof sq ft', 'sqft = footprint_sqft × (1 ÷ cos(pitch°))'],
      ['Sq ft to squares', 'squares = ceil(sqft ÷ 100)'],
      ['With waste', 'total = ceil(squares × (1 + waste%))'],
      ['Hip roof factor', 'hip_sqft = sqft × 1.04'],
    ],
    faqs: [
      ['How do I calculate roof square footage?', 'footprint_sqft × pitch_factor. 2,000 sq ft at 6:12 (factor 1.118) = 2,236 sq ft. Divide by 100 for squares.'],
      ['Is house square footage the same as roof?', 'No. Roof area = footprint × pitch factor. At 6:12, roof is 11.8% larger than footprint. At 12:12, 41.4% larger.'],
      ['How many squares is 2,000 sq ft roof?', '2,000 ÷ 100 = 20 squares. With 12% waste: 20 × 1.12 = 22.4 → 23 squares.'],
      ['Best free roof sq ft calculator?', 'One that takes footprint + pitch, calculates sq ft and squares with waste. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-sheathing-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Sheathing Calculator',
    mTitle: 'Free Roof Sheathing Calculator - Plywood & OSB Sheets | QuoteCore+',
    mDesc: 'Free roof sheathing calculator. Calculate plywood and OSB sheet quantities from roof area. Includes waste and cut patterns. No signup required.',
    ogTitle: 'Free Roof Sheathing Calculator - Plywood & OSB',
    ogDesc: 'Free roof sheathing calculator. Sheet quantities from roof area.',
    h1: 'Roof Sheathing Calculator',
    hero: 'Calculate roof sheathing (plywood/OSB) sheet quantities from roof area. Enter dimensions and pitch for sheet count with waste and cut waste. Free, no signup.',
    tipsH: 'Roof sheathing - did you know?',
    tips: [
      ['Standard sheet sizes', 'UK: 2440 × 1220mm (8 × 4 ft) = 2.98 m² per sheet. US: 4 × 8 ft = 32 sq ft. Thickness: 12mm (UK min for rafters at 400mm), 15mm (600mm centres), 18mm (UK general). US: 7/16" OSB standard, 1/2" or 5/8" for high wind.'],
      ['Sheet calculation', 'Sheets = roof_area ÷ sheet_area × (1 + waste%). At 10% waste: 100 m² ÷ 2.98 × 1.10 = 36.9 → 37 sheets. For US: 2,236 sq ft ÷ 32 × 1.10 = 76.9 → 77 sheets.'],
      ['Waste for sheathing', 'Standard: 10%. Hips/valleys: 15% (diagonal cuts waste more). Staggered pattern (recommended): 10-12%. H-clips between sheets on rafters for spacing and support.'],
      ['Nailing schedule for sheathing', '8d ring-shank nails at 150mm OC on edges, 300mm OC in field (UK: 50mm nails at 150mm edges, 300mm field). That is ~32 nails per 8×4 sheet. 1 box (5,000 nails) covers ~150 sheets.'],
    ],
    formulas: [
      ['Sheets needed', 'sheets = ceil(roof_area ÷ sheet_area × (1 + waste%))'],
      ['Sheet area (metric)', '2.98 m² per 2440×1220mm sheet'],
      ['Sheet area (imperial)', '32 sq ft per 4×8 sheet'],
      ['Nails', 'nails = sheets × 32'],
    ],
    faqs: [
      ['How many sheets of plywood do I need for a roof?', 'roof_area ÷ sheet_area × (1 + waste%). 100 m² at 10% waste: 100 ÷ 2.98 × 1.10 = 37 sheets. US: 2,236 sq ft ÷ 32 × 1.10 = 77 sheets.'],
      ['What thickness for roof sheathing?', 'UK: 12mm min at 400mm centres, 15mm at 600mm. US: 7/16" OSB standard, 5/8" for high wind zones. Check span ratings on panel stamp.'],
      ['How much waste for roof sheathing?', '10% standard, 15% for roofs with hips/valleys (diagonal cuts). Staggered patterns: 10-12%.'],
      ['Best free roof sheathing calculator?', 'One that calculates sheets, nails, and waste from roof area. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roofing-waste-calculator',
    defaultTab: 'smart-component',
    name: 'Roofing Waste Calculator',
    mTitle: 'Free Roofing Waste Calculator - Calculate Cut & Scrap Waste | QuoteCore+',
    mDesc: 'Free roofing waste calculator. Calculate cut waste, scrap, and overage for tiles, shingles, and sheets. No signup required.',
    ogTitle: 'Free Roofing Waste Calculator - Cut & Scrap',
    ogDesc: 'Free roofing waste calculator. Cut waste and overage.',
    h1: 'Roofing Waste Calculator',
    hero: 'Calculate roofing waste allowance for any material. Get precise overage for cuts, valleys, hips, and complex roof shapes. Free, no signup.',
    tipsH: 'Roofing waste - did you know?',
    tips: [
      ['Why waste matters', 'Under-ordering by 5% can stop a job mid-roof. Over-ordering by 15% wastes money (most suppliers charge restocking fees). Precise waste calculation saves both time and money.'],
      ['Waste by roof complexity', 'Simple gable: 5-10%. Gable with 1 valley: 10-12%. Hip roof: 15-20%. Hip with valleys and dormers: 20-25%. Every valley, hip, or penetration adds ~2-3% waste.'],
      ['Waste by material type', 'Concrete tiles: 5-10%. Clay tiles: 10-15% (breakage). Slate: 15-20% (splitting). Metal sheets: 5% (minimal cuts). Shingles: 10-15%. Membrane: 5% (cuts at upstands).'],
      ['Skip and disposal', 'Strip a roof generates ~10-15 kg/m² of waste (old tiles + felt + battens). 100 m² roof = 1-1.5 tonnes. Order a 6-yard skip minimum. Some tile merchants take back undamaged stripped tiles.'],
    ],
    formulas: [
      ['Material with waste', 'qty = base_qty × (1 + waste%)'],
      ['Waste by complexity', 'waste% = 5% + valleys×2% + hips×1.5% + dormers×2%'],
      ['Strip waste weight', 'kg = roof_area × 12 kg/m²'],
      ['Skip size', 'yards = roof_area × 0.06'],
    ],
    faqs: [
      ['How much waste should I add for roofing?', '5-10% gable, 10-12% with valley, 15-20% hip roof, 20-25% complex hip with dormers. Each valley/hip/dormer adds 2-3%.'],
      ['How much waste for concrete tiles vs clay?', 'Concrete: 5-10%. Clay: 10-15% (breakage). Slate: 15-20%. Metal: 5%. Shingles: 10-15%.'],
      ['How much skip space for roof strip waste?', '~12 kg/m² of roof. 100 m² = 1.2 tonnes = 6-yard skip minimum. Some merchants take back undamaged tiles.'],
      ['Best free roofing waste calculator?', 'One that factors roof complexity, material type, and disposal. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-sheet-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Sheet Calculator',
    mTitle: 'Free Roof Sheet Calculator - Corrugated & Polycarbonate Sheets | QuoteCore+',
    mDesc: 'Free roof sheet calculator. Calculate corrugated, polycarbonate, and profiled sheet quantities from roof dimensions. No signup required.',
    ogTitle: 'Free Roof Sheet Calculator - Corrugated & Poly',
    ogDesc: 'Free roof sheet calculator. Sheet quantities from dimensions.',
    h1: 'Roof Sheet Calculator',
    hero: 'Calculate roof sheet quantities - corrugated iron, polycarbonate, profiled metal - from roof dimensions and pitch. Account for laps and waste. Free, no signup.',
    tipsH: 'Roof sheets - did you know?',
    tips: [
      ['Effective coverage width', 'Sheets have a nominal width and an effective width (after side laps). Corrugated 1000mm profile: ~750mm effective (250mm lap). Box profile: ~1000mm effective (50mm lap). Always use effective width for sheet count.'],
      ['Sheet length calculation', 'Sheet length = rafter length + overhang + 50mm trim. If rafter exceeds available sheet length (typically 6m), use two sheets with 200-300mm end lap. Lower pitch = larger end lap.'],
      ['Polycarbonate vs metal', 'Polycarbonate: same profile, lighter, UV-coated. Coverage calculation is identical. But poly needs more fixings (every corrugation) and wider lap sealant.寿命: 15-20 years vs 40+ for metal.'],
      ['Flashing and accessories', 'Ridge flashing: 1 per 3m of ridge. Apron flashing: at top of lean-to roofs. Verge trim: at gable ends. Closure strips: foam strips sealing corrugation gaps at ridge and eaves. Budget ~15% of sheet cost for accessories.'],
    ],
    formulas: [
      ['Sheets per slope', 'sheets = ceil(roof_width ÷ effective_width)'],
      ['Sheet length', 'length = rafter_length + overhang + 50mm'],
      ['Total sheets', 'total = sheets_per_slope × number_of_slopes'],
      ['Fixings', 'fixings = area × 8 per m²'],
    ],
    faqs: [
      ['How do I calculate corrugated roof sheets?', 'ceil(roof_width ÷ effective_width) per slope. 10m wide roof at 750mm effective: 14 sheets. Sheet length = rafter + overhang + trim.'],
      ['What is the overlap for corrugated sheets?', 'Side lap: 1 corrugation (~250mm). End lap: 150-300mm depending on pitch. Lower pitch = bigger end lap.'],
      ['How do I calculate polycarbonate sheets?', 'Same as metal - same profile, same effective width. But poly needs more fixings (every corrugation) and wider sealant.'],
      ['Best free roof sheet calculator?', 'One that handles effective width, laps, sheet length, and fixings. This tool does all, free.'],
    ],
  },
];
