import type { SlugDef } from './roofingSlugs1';

export const SLUGS_2: SlugDef[] = [
  {
    slug: 'free-roofing-material-calculator',
    defaultTab: 'smart-component',
    name: 'Roofing Material Calculator',
    mTitle: 'Free Roofing Material Calculator - Tiles, Sheets & Quantities | QuoteCore+',
    mDesc: 'Free roofing material calculator. Calculate tile, sheet, and shingle quantities from roof area and pitch. Includes waste allowance. No signup required.',
    ogTitle: 'Free Roofing Material Calculator - Tiles & Sheets',
    ogDesc: 'Free roofing material calculator. Quantities from roof area and pitch.',
    h1: 'Roofing Material Calculator',
    hero: 'Calculate roofing material quantities from roof area and pitch. Enter dimensions, choose material type, and get quantities with waste allowance included. Free, no signup.',
    tipsH: 'Roofing materials - did you know?',
    tips: [
      ['How material quantities are calculated', 'Quantity = roof_area × (1 + waste%) ÷ coverage_per_unit. For concrete tiles at 10% waste covering 122 m²: 122 × 1.10 ÷ 0.33 (tiles per m² at ~3.3 tiles/m²) = ~407 tiles.'],
      ['Coverage varies by material type', 'Concrete tiles: ~9-12 per m². Clay tiles: ~10-15 per m². Slate (500mm): ~20 per m². Metal sheets: calculate by sheet area minus laps. Shingles: 3 bundles per square (100 sq ft).'],
      ['Why waste percentage matters', 'Waste covers cuts at valleys, hips, chimneys, and edges. Concrete tiles: 5-10%. Clay tiles: 10-15% (fragile). Metal sheets: 5%. Shingles: 10-15%. Add 5% extra for complex roofs.'],
      ['Ordering vs calculating', 'Always round UP to the nearest pack/batch quantity. Suppliers often sell tiles in batches of 100, sheets in 3m lengths, shingles in bundles of ~10 m². Check supplier pack sizes before ordering.'],
    ],
    formulas: [
      ['Material quantity', 'qty = area × (1 + waste%) ÷ coverage'],
      ['Roof area from plan', 'area = plan_area × (1 ÷ cos(pitch°))'],
      ['Tiles needed', 'tiles = area × tiles_per_m² × (1 + waste%)'],
      ['Squares (shingles)', 'squares = roof_area_sqft ÷ 100'],
    ],
    faqs: [
      ['How do I calculate how many roof tiles I need?', 'roof_area × tiles_per_m² × (1 + waste%). For 122 m² at 10 tiles/m² and 10% waste: 122 × 10 × 1.10 = 1,342 tiles.'],
      ['How many bundles of shingles do I need?', '3 bundles per square (100 sq ft). For 1,500 sq ft roof at 15% waste: 15 × 1.15 = 17.25 → 18 squares → 54 bundles.'],
      ['What waste percentage for roofing materials?', 'Concrete tiles 5-10%, clay tiles 10-15%, metal sheets 5%, shingles 10-15%. Add 5% extra for complex roofs.'],
      ['Best free roofing material calculator?', 'One that takes roof area + pitch, applies waste, and outputs quantities per material type. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-metal-roofing-calculator',
    defaultTab: 'roof-area',
    name: 'Metal Roofing Calculator',
    mTitle: 'Free Metal Roofing Calculator - Sheets, Cost & Waste | QuoteCore+',
    mDesc: 'Free metal roofing calculator. Calculate sheet quantities, overlaps, and costs from roof dimensions. No signup required.',
    ogTitle: 'Free Metal Roofing Calculator - Sheets & Cost',
    ogDesc: 'Free metal roofing calculator. Sheet quantities and costs.',
    h1: 'Metal Roofing Calculator',
    hero: 'Calculate metal roofing sheet quantities from roof dimensions and pitch. Account for overlaps, waste, and screw counts. Free, no signup.',
    tipsH: 'Metal roofing - did you know?',
    tips: [
      ['How metal sheets are measured', 'Metal roofing sheets are sold by length (e.g. 3m, 4m, 5m) with a standard coverage width (typically 1000mm profile, ~760mm effective after side laps). Calculate sheets needed: roof_width ÷ effective_width.'],
      ['Side laps and end laps', 'Each sheet overlaps the next by one corrugation (side lap) and by 150-300mm at horizontal joints (end lap). Effective coverage width = profile width − side lap. For 1000mm profile with 250mm lap: 750mm effective.'],
      ['Minimum pitch for metal roofing', 'Corrugated: 5° minimum (10° recommended). Standing seam: 3° minimum. Trimrib/Mini Orb: 5°. Below these, water can travel back up the corrugations under wind pressure.'],
      ['Screw and accessory calculations', 'Approximately 8-10 screws per m² for corrugated, 3-5 per m² for standing seam (hidden fix). Add ridge caps, fascia trim, flashing, and closure strips - typically 10-15% of sheet cost for accessories.'],
    ],
    formulas: [
      ['Sheets needed', 'sheets = ceil(roof_width ÷ effective_width)'],
      ['Effective width', 'effective = profile_width − side_lap'],
      ['Sheet length', 'length = rafter_length + overhang + 50mm trim'],
      ['Screw count', 'screws ≈ area × 8 per m²'],
    ],
    faqs: [
      ['How do I calculate metal roofing sheets?', 'Divide roof width by effective sheet width (profile minus lap). For 10m wide roof at 750mm effective: ceil(10 ÷ 0.75) = 14 sheets per slope.'],
      ['What is the overlap for metal roofing?', 'Side lap: one corrugation (~250mm). End lap: 150-300mm depending on pitch. Lower pitch = larger end lap.'],
      ['Minimum pitch for metal roof?', 'Corrugated: 5° min (10° recommended). Standing seam: 3° min. Below these, water backs up under wind.'],
      ['Best free metal roofing calculator?', 'One that handles sheet coverage, laps, screw counts, and waste. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-shingle-calculator',
    defaultTab: 'roof-area',
    name: 'Shingle Calculator',
    mTitle: 'Free Shingle Calculator - Bundles, Squares & Waste | QuoteCore+',
    mDesc: 'Free shingle calculator. Calculate shingle bundles and squares from roof area. Includes waste and starter/ridge amounts. No signup required.',
    ogTitle: 'Free Shingle Calculator - Bundles & Squares',
    ogDesc: 'Free shingle calculator. Bundles and squares from roof area.',
    h1: 'Shingle Calculator',
    hero: 'Calculate asphalt shingle quantities from roof area. Get bundles, squares, and underlayment with waste allowance. Imperial and metric. Free, no signup.',
    tipsH: 'Shingles - did you know?',
    tips: [
      ['What is a "square" of shingles?', 'One square covers 100 square feet. Most architectural shingles come 3 bundles per square (33.3 sq ft per bundle). Some premium brands are 4 bundles per square.'],
      ['Waste percentage for shingles', 'Straight cuts: 10-12%. Diagonal/herringbone: 15-20%. Valleys, hips, and dormers add 2-3 bundles each. Starter strip: 1 bundle per 40 linear feet of eaves. Ridge cap: 1 bundle per 35 linear feet.'],
      ['Underlayment calculation', 'Felt underlayment: 1 roll (400 sq ft) per 4 squares. Synthetic underlayment: 1 roll (1000 sq ft) per 10 squares. Ice & water shield: required at eaves in cold climates - 2 rows minimum.'],
      ['Nail quantities', 'Standard 4-nail pattern: ~320 nails per square. 6-nail pattern (high wind): ~480 per square. 1 box (5,000 nails) covers ~15 squares at 4-nail or ~10 squares at 6-nail.'],
    ],
    formulas: [
      ['Squares needed', 'squares = ceil(roof_area_sqft ÷ 100 × (1 + waste%))'],
      ['Bundles', 'bundles = squares × 3 (standard)'],
      ['Starter strips', 'starter = ceil(eaves_length_ft ÷ 40)'],
      ['Ridge caps', 'ridge = ceil(ridge_length_ft ÷ 35)'],
    ],
    faqs: [
      ['How many bundles of shingles do I need?', 'Roof area in sq ft ÷ 100 × (1 + waste) × 3 bundles/square. 1,500 sq ft at 12% waste: 15 × 1.12 = 16.8 → 17 squares → 51 bundles.'],
      ['What is a square of shingles?', 'One square = 100 sq ft of coverage. Most architectural shingles = 3 bundles per square. Check packaging - some premium brands are 4 bundles.'],
      ['How much waste for shingles?', '10-12% for straight cuts, 15-20% for diagonal patterns. Add 2-3 bundles per valley/hip/dormer for cuts.'],
      ['Best free shingle calculator?', 'One that calculates bundles, squares, starter, ridge, and underlayment. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-tile-calculator',
    defaultTab: 'roof-area',
    name: 'Roof Tile Calculator',
    mTitle: 'Free Roof Tile Calculator - Concrete & Clay Tile Quantities | QuoteCore+',
    mDesc: 'Free roof tile calculator. Calculate concrete and clay tile quantities from roof area and pitch. Includes waste and batten spacing. No signup required.',
    ogTitle: 'Free Roof Tile Calculator - Concrete & Clay',
    ogDesc: 'Free roof tile calculator. Tile quantities from roof area.',
    h1: 'Roof Tile Calculator',
    hero: 'Calculate roof tile quantities from roof area and pitch. Concrete tiles, clay tiles, and slate - with waste allowance and batten spacing. Free, no signup.',
    tipsH: 'Roof tiles - did you know?',
    tips: [
      ['Tiles per m² by type', 'Concrete interlocking: 9-12/m². Clay pantile: 10-15/m². Plain tile: 60/m². Slate (500×250mm): 20/m² at 75mm headlap. Always check manufacturer specs.'],
      ['Headlap and batten gauge', 'Headlap (how much each tile overlaps the one below) determines batten spacing. Concrete interlocking at 35°: 100mm headlap, 345mm batten gauge. Plain tiles: 65mm headlap, 100mm gauge.'],
      ['Minimum pitch for tiles', 'Concrete interlocking: 17.5° minimum (15° with special designs). Clay pantile: 22.5°. Plain tiles: 35°. Slate: 20°+ (30°+ for small formats). Below minimums, water tracks back under tiles.'],
      ['Ridge, hip, and valley tiles', 'Ridge tiles: 1 per 400mm of ridge length. Hip tiles: 1 per 400mm of hip length. Valley: cut tiles at 45°, add 15% waste to valley rows. Eaves: 1 row of eaves tiles (half-width) at bottom edge.'],
    ],
    formulas: [
      ['Tiles needed', 'tiles = area × tiles_per_m² × (1 + waste%)'],
      ['Batten length', 'battens = area ÷ batten_gauge × batten_width_factor'],
      ['Roof area from plan', 'area = plan_area × (1 ÷ cos(pitch°))'],
      ['Ridge tiles', 'ridge = ridge_length ÷ 0.4'],
    ],
    faqs: [
      ['How many roof tiles do I need?', 'area × tiles_per_m² × (1 + waste%). 122 m² at 10 tiles/m² and 10% waste: 122 × 10 × 1.10 = 1,342 tiles.'],
      ['How many concrete tiles per m²?', 'Concrete interlocking: 9-12/m². Clay pantile: 10-15/m². Plain tile: 60/m². Check manufacturer specs for exact coverage.'],
      ['What batten spacing for roof tiles?', 'Depends on tile type and headlap. Concrete at 35°: 345mm gauge. Plain tiles: 100mm gauge. Always follow manufacturer batten gauge tables.'],
      ['Best free roof tile calculator?', 'One that handles tile counts, batten spacing, and ridge/hip extras. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-flat-roof-calculator',
    defaultTab: 'roof-area',
    name: 'Flat Roof Calculator',
    mTitle: 'Free Flat Roof Calculator - Area, Falls & Membrane | QuoteCore+',
    mDesc: 'Free flat roof calculator. Calculate flat roof area, membrane quantities, falls, and drainage. No signup required.',
    ogTitle: 'Free Flat Roof Calculator - Area & Membrane',
    ogDesc: 'Free flat roof calculator. Area, falls, and membrane quantities.',
    h1: 'Flat Roof Calculator',
    hero: 'Calculate flat roof area, drainage falls, and membrane quantities. Enter dimensions, specify fall ratio, and get material quantities. Free, no signup.',
    tipsH: 'Flat roofs - did you know?',
    tips: [
      ['Flat roofs aren\'t actually flat', 'Building regs require a minimum 1:80 fall (1.25% slope, ~0.7°) for water drainage. Most flat roofs are 1:40 to 1:60 (1.4° to 2.4°). The fall directs water to outlets or gutters.'],
      ['Membrane types and coverage', 'Bitumen felt: 2-3 layers, each covering full area (multiply by layers). EPDM rubber: single sheet, area + 150mm perimeter upturn. GRP fibreglass: resin + matting, ~1.5kg/m² resin per layer. TPO: single-ple, similar to EPDM.'],
      ['Insulation on flat roofs', 'Warm deck: insulation above the deck (most common). Cold deck: insulation below (requires ventilation). Typical PIR insulation: 100-150mm for U-value compliance. Calculate by area × thickness.'],
      ['Drainage and outlet sizing', 'Flat roof outlets sized by plan area and rainfall intensity. 1 outlet per 40-80 m² (UK typical). Check fall directs water to outlets - any ponding area is a failure point.'],
    ],
    formulas: [
      ['Flat roof area', 'area = length × width'],
      ['Fall amount', 'fall = run × (1 ÷ ratio)'],
      ['Membrane quantity', 'membrane = area × layers + perimeter × 0.15'],
      ['Insulation volume', 'volume = area × thickness_m'],
    ],
    faqs: [
      ['What fall does a flat roof need?', 'Minimum 1:80 (0.7°) per UK Building Regs. Recommended 1:40 (1.4°) to 1:60 (1.0°) for positive drainage.'],
      ['How much membrane for a flat roof?', 'Area × number of layers + 150mm upstand perimeter. 3-layer felt on 50 m² roof: 50 × 3 = 150 m² + ~6 m² upstands = ~156 m².'],
      ['What insulation thickness for flat roofs?', 'Typically 100-150mm PIR for U-value compliance. Check Part L for current requirements. Calculate volume = area × thickness.'],
      ['Best free flat roof calculator?', 'One that handles area, falls, membrane layers, and insulation. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-gable-roof-calculator',
    defaultTab: 'roof-area',
    name: 'Gable Roof Calculator',
    mTitle: 'Free Gable Roof Calculator - Area, Rafters & Materials | QuoteCore+',
    mDesc: 'Free gable roof calculator. Calculate gable roof area, rafter lengths, and material quantities from span and pitch. No signup required.',
    ogTitle: 'Free Gable Roof Calculator - Area & Rafters',
    ogDesc: 'Free gable roof calculator. Area, rafters, and materials.',
    h1: 'Gable Roof Calculator',
    hero: 'Calculate gable roof area, rafter lengths, and material quantities from building span and pitch. Includes both slopes, waste, and overhang. Free, no signup.',
    tipsH: 'Gable roofs - did you know?',
    tips: [
      ['How a gable roof works', 'A gable roof has two slopes meeting at a central ridge. Each slope is a simple rectangle. Total roof area = 2 × (run ÷ cos(pitch°)) × building_length. At 35°, 4m run, 10m building: 2 × 4.88 × 10 = 97.6 m².'],
      ['Gable vs hip - which costs less?', 'Gable roofs are simpler and cheaper: fewer rafters, no compound cuts, less waste (10% vs 15-20% for hips). Gable roofs also have better loft space. But they are less wind-resistant than hip roofs.'],
      ['Rafter count for a gable roof', 'Rafters at 400mm centres: building_length ÷ 0.4 + 1 pairs. For 10m building: 26 pairs = 52 rafters. At 600mm centres: 18 pairs = 36 rafters. Add 2 for gable ladder overhangs.'],
      ['Gable end area calculation', 'Gable triangle area = run × (run × tan(pitch°)) ÷ 2. At 4m run and 35°: 4 × (4 × 0.700) ÷ 2 = 5.6 m² per gable. Used for wall material and vent calculations.'],
    ],
    formulas: [
      ['Total roof area', 'area = 2 × (run ÷ cos(pitch°)) × length'],
      ['Rafter length', 'rafter = run ÷ cos(pitch°)'],
      ['Rafter pairs', 'pairs = ceil(length ÷ spacing) + 1'],
      ['Gable end area', 'gable = run × run × tan(pitch°) ÷ 2'],
    ],
    faqs: [
      ['How do I calculate gable roof area?', '2 × (run ÷ cos(pitch°)) × building_length. At 35°, 4m run, 10m building: 2 × 4.88 × 10 = 97.6 m².'],
      ['How many rafters for a gable roof?', 'At 400mm centres: length ÷ 0.4 + 1 pairs. 10m building = 26 pairs = 52 rafters. Add 2 for gable ladders.'],
      ['Gable vs hip roof cost?', 'Gable is simpler: fewer rafters, no compound cuts, 10% waste vs 15-20% for hip. Gable is typically 20-30% cheaper.'],
      ['Best free gable roof calculator?', 'One that handles both slopes, rafter counts, and material quantities. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-hip-roof-calculator',
    defaultTab: 'roof-area',
    name: 'Hip Roof Calculator',
    mTitle: 'Free Hip Roof Calculator - Area, Hip Rafters & Materials | QuoteCore+',
    mDesc: 'Free hip roof calculator. Calculate hip roof area, hip rafter lengths, and material quantities. No signup required.',
    ogTitle: 'Free Hip Roof Calculator - Area & Hip Rafters',
    ogDesc: 'Free hip roof calculator. Area, hip lengths, and materials.',
    h1: 'Hip Roof Calculator',
    hero: 'Calculate hip roof area, hip rafter lengths, and material quantities from building dimensions and pitch. Includes all four slopes and hip/valley lengths. Free, no signup.',
    tipsH: 'Hip roofs - did you know?',
    tips: [
      ['How hip roof area differs from gable', 'A hip roof has 4 slopes instead of 2. The plan area × pitch factor gives total surface area, but hip ends are triangular. For a square building at 35°: total area = plan × 1.221. For rectangles, calculate each slope separately.'],
      ['Hip rafter count', 'A rectangular hip roof has 4 hip rafters (one per corner). Each runs from corner to ridge. Common rafters run between hips. At 400mm centres, common rafter count = (ridge_length + 2 × run) ÷ 0.4 + 1.'],
      ['Why hip roofs waste more material', 'Hip roofs have compound cuts at every hip junction, triangular hip-end slopes, and shorter common rafters near the hips. Waste is typically 15-20% vs 10% for gable roofs.'],
      ['Hip roof structural considerations', 'Hip roofs are more wind-resistant than gable roofs (no large flat gable ends to catch wind). They distribute load to all four walls. But they require more structural elements: hip rafters, jack rafters, and ridge bracing.'],
    ],
    formulas: [
      ['Total hip roof area', 'area = plan_area × (1 ÷ cos(pitch°)) × 1.04'],
      ['Hip rafter length', 'hip = hip_run × sqrt((1/cos(pitch°))² + 1)'],
      ['Common rafter', 'rafter = run ÷ cos(pitch°)'],
      ['Jack rafter (shortest)', 'jack = (hip_spacing ÷ cos(pitch°))'],
    ],
    faqs: [
      ['How do I calculate hip roof area?', 'Plan area × pitch factor × ~1.04 (hip end factor). At 35°, 100 m² plan: 100 × 1.221 × 1.04 = 127 m². For precision, calculate each of the 4 slopes separately.'],
      ['How many hip rafters does a hip roof have?', '4 hip rafters (one per corner) for a rectangular building. Plus common rafters between hips at regular centres.'],
      ['Why does a hip roof cost more than a gable?', 'More rafters, compound cuts, 15-20% waste vs 10%, shorter jack rafters near hips. Typically 20-30% more expensive.'],
      ['Best free hip roof calculator?', 'One that handles all 4 slopes, hip lengths, jack rafters, and waste. This tool does all, free.'],
    ],
  },
];
