import type { SlugDef } from './roofingSlugs1';

export const SLUGS_4: SlugDef[] = [
  {
    slug: 'free-guttering-calculator',
    defaultTab: 'angle-finder',
    name: 'Guttering Calculator',
    mTitle: 'Free Guttering Calculator - Gutters, Downpipes & Fascia | QuoteCore+',
    mDesc: 'Free guttering calculator. Calculate gutter lengths, downpipe quantities, and fascia boards from roof dimensions. No signup required.',
    ogTitle: 'Free Guttering Calculator - Gutters & Downpipes',
    ogDesc: 'Free guttering calculator. Gutter lengths and downpipes.',
    h1: 'Guttering Calculator',
    hero: 'Calculate gutter lengths, downpipe quantities, and fascia board requirements from roof dimensions. Includes runoff capacity checks. Free, no signup.',
    tipsH: 'Guttering - did you know?',
    tips: [
      ['Gutter sizing from roof area', 'Effective roof area for gutter sizing = plan area × pitch factor (bigger roof = more water). Half-round 112mm gutter handles ~36 m² effective area per downpipe. Square 125mm: ~50 m². Always check manufacturer flow rates.'],
      ['Downpipe spacing', 'UK rule of thumb: 1 downpipe per 6m of gutter run, or per 36 m² effective roof area (whichever is less). At 35° pitch with 100 m² plan (122 m² effective): 122 ÷ 36 = 3.4 → 4 downpipes minimum.'],
      ['Fascia and soffit calculation', 'Fascia length = total eaves length (both sides for gable, all 4 sides for hip). Soffit area = eaves overhang × perimeter. Standard overhang: 150-300mm. Fascia board: 150-200mm deep typically.'],
      ['Rainwater capacity check', 'UK design rainfall: 75mm/hour intensity. Each downpipe should handle roof_area × 75mm/h. A 68mm circular downpipe handles ~12 m² at 75mm/h. A 100mm square: ~50 m². Size up in high-rainfall regions.'],
    ],
    formulas: [
      ['Effective roof area', 'effective = plan_area × (1 ÷ cos(pitch°))'],
      ['Downpipes needed', 'downpipes = ceil(effective_area ÷ m²_per_downpipe)'],
      ['Gutter length', 'gutter = eaves_length (gable: 2 sides; hip: 4 sides)'],
      ['Fascia length', 'fascia = eaves_perimeter'],
    ],
    faqs: [
      ['How do I calculate gutter length?', 'Total eaves length. Gable roof: 2 × building_length. Hip roof: perimeter of building. Add 10% for cuts and joints.'],
      ['How many downpipes do I need?', '1 per 36 m² effective roof area (half-round 112mm). At 35°, 100 m² plan = 122 m² effective → 4 downpipes.'],
      ['What size gutters for my roof?', '112mm half-round: up to 36 m²/downpipe. 125mm square: up to 50 m². 150mm industrial: up to 100 m². Check manufacturer flow rates.'],
      ['Best free guttering calculator?', 'One that handles gutter length, downpipe count, and runoff capacity. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-flashing-calculator',
    defaultTab: 'angle-finder',
    name: 'Roof Flashing Calculator',
    mTitle: 'Free Roof Flashing Calculator - Apron, Step & Valley Flashing | QuoteCore+',
    mDesc: 'Free roof flashing calculator. Calculate apron, step, and valley flashing quantities from roof dimensions and junctions. No signup required.',
    ogTitle: 'Free Roof Flashing Calculator - Apron & Step',
    ogDesc: 'Free roof flashing calculator. Flashing quantities and lengths.',
    h1: 'Roof Flashing Calculator',
    hero: 'Calculate roof flashing quantities - apron, step, valley, and chimney flashing - from roof dimensions and junction details. Free, no signup.',
    tipsH: 'Roof flashing - did you know?',
    tips: [
      ['Types of flashing and where they go', 'Apron flashing: where a roof meets a vertical wall above (e.g. lean-to against house). Step flashing: where a roof slope meets a side wall. Valley flashing: in valleys. Chimney flashing: base + step + apron + back gutter. Damp-proof courses (DPC) under all.'],
      ['Flashing material types', 'Lead: traditional, long-lasting (60+ years), expensive. Colour-coated aluminium: cheaper, 30 years. Zinc: 50 years, self-healing. GRP/pre-formed: modern, quick to install. Flashing band/tape: temporary only.'],
      ['Step flashing calculation', 'Each step flashing piece covers ~100mm of horizontal wall length. Pieces = wall_length ÷ 0.1. At 2m chimney wall: 20 pieces each side. Each piece: 150mm × 200mm minimum, lapped 75mm.'],
      ['Valley flashing width', 'Valley flashing width depends on pitch and water volume. Low pitch (under 20°): 450mm minimum. Normal pitch (20-40°): 300mm. Steep (40°+): 225mm. Always allow 75mm upstand each side. Center the valley trough.'],
    ],
    formulas: [
      ['Apron flashing length', 'apron = wall_length + 150mm each end'],
      ['Step flashing pieces', 'pieces = ceil(wall_length ÷ 0.1) × 2 sides'],
      ['Valley flashing', 'valley = valley_length + 150mm × 2 ends'],
      ['Chimney flashing', 'chimney = base + step + apron + back gutter'],
    ],
    faqs: [
      ['How do I calculate step flashing?', 'Pieces = wall_length ÷ 100mm × 2 sides. 2m chimney: 20 pieces per side × 2 = 40 pieces. Each piece: 150 × 200mm minimum.'],
      ['What width valley flashing do I need?', 'Low pitch (<20°): 450mm. Normal (20-40°): 300mm. Steep (40°+): 225mm. Add 75mm upstand each side.'],
      ['Lead vs aluminium flashing?', 'Lead: 60+ year life, expensive, heavy. Aluminium: 30 years, cheaper, lighter. Zinc: 50 years, mid-price. Choose by budget and building style.'],
      ['Best free roof flashing calculator?', 'One that handles apron, step, valley, and chimney flashing quantities. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roof-replacement-cost-calculator',
    defaultTab: 'smart-component',
    name: 'Roof Replacement Cost Calculator',
    mTitle: 'Free Roof Replacement Cost Calculator - Estimate Replacement | QuoteCore+',
    mDesc: 'Free roof replacement cost calculator. Estimate material, labour, and skip costs for roof replacement. No signup required.',
    ogTitle: 'Free Roof Replacement Cost Calculator',
    ogDesc: 'Free roof replacement cost calculator. Estimate full replacement.',
    h1: 'Roof Replacement Cost Calculator',
    hero: 'Estimate roof replacement costs from dimensions and material choice. Get material, labour, skip, and scaffold cost breakdowns. Free, no signup.',
    tipsH: 'Roof replacement - did you know?',
    tips: [
      ['Cost components of a roof replacement', 'Materials (30-40%): tiles, membrane, battens, nails. Labour (40-50%): strip, dispose, re-batten, re-tile. Scaffolding (10-15%): front and rear access. Skip (2-5%): roofing waste is bulky. Extras: flashing, verges, ridge ventilation.'],
      ['Cost per m² by material', 'Concrete tile re-roof: £60-90/m². Clay tile: £80-120/m². Slate: £100-180/m². Metal standing seam: £70-110/m². EPDM flat roof: £50-80/m². These are UK 2024 averages including labour.'],
      ['Strip and dispose costs', 'Stripping adds ~£15-25/m² to the job. Disposal: 1 tonne of tile per ~8 m² of roof. 100 m² roof = 12.5 tonnes. Skip hire: £250-400. Some merchants take back tiles (reduces skip cost). Asbestos cement: specialist disposal, £500+.'],
      ['When to repair vs replace', 'Repair if: <20% of tiles damaged, isolated leak, flashings failed. Replace if: >30% tiles damaged, sagging roof, multiple leaks, no membrane (pre-1970s), battens rotten. Borderline (20-30%): get a structural survey first.'],
    ],
    formulas: [
      ['Total cost', 'total = (materials + labour + scaffold + skip) × roof_area'],
      ['Material cost', 'materials = area × material_rate_per_m²'],
      ['Labour cost', 'labour = area × labour_rate_per_m²'],
      ['Strip cost', 'strip = area × strip_rate_per_m²'],
    ],
    faqs: [
      ['How much does a roof replacement cost?', 'UK: £60-90/m² concrete, £80-120/m² clay, £100-180/m² slate, £70-110/m² metal. 100 m² concrete tile re-roof: £6,000-9,000+ including labour and scaffold.'],
      ['How much to strip and dispose of old roof?', '£15-25/m². 100 m² roof generates ~12.5 tonnes of waste. Skip: £250-400. Some merchants take back undamaged tiles.'],
      ['Should I repair or replace my roof?', 'Repair if <20% damage. Replace if >30% damage, sagging, multiple leaks, no membrane, or rotten battens. 20-30%: get a survey.'],
      ['Best free roof replacement cost calculator?', 'One that breaks down materials, labour, scaffold, and disposal. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roofing-takeoff-calculator',
    defaultTab: 'roof-area',
    name: 'Roofing Takeoff Calculator',
    mTitle: 'Free Roofing Takeoff Calculator - Materials, Areas & Lengths | QuoteCore+',
    mDesc: 'Free roofing takeoff calculator. Calculate all roofing materials - tiles, battens, membrane, flashings - from roof dimensions. No signup required.',
    ogTitle: 'Free Roofing Takeoff Calculator - Full Material Takeoff',
    ogDesc: 'Free roofing takeoff calculator. Complete material quantities.',
    h1: 'Roofing Takeoff Calculator',
    hero: 'Complete roofing material takeoff from roof dimensions and pitch. Get tiles, battens, membrane, felt, fixings, and flashing quantities in one calculation. Free, no signup.',
    tipsH: 'Roofing takeoff - did you know?',
    tips: [
      ['What a full takeoff includes', 'Tiles (by type and count), underlay/membrane (m² + rolls), battens (linear metres), nails/screws (by type), ridge/hip tiles, valley gutter, flashing (apron/step/valley), verge trim, ventilation. A professional takeoff leaves nothing to guess.'],
      ['Batten calculation', 'Batten length = roof_area ÷ batten_gauge. At 35° pitch with 345mm batten gauge: 100 m² ÷ 0.345 = 290 linear metres of batten per slope. Add 10% for cuts. 25mm × 50mm treated timber is UK standard.'],
      ['Membrane/underlay calculation', 'Membrane rolls: typically 1.5m × 50m = 75 m² per roll. Coverage with 150mm horizontal laps: ~60 m² effective. 100 m² roof: 100 ÷ 60 = 1.67 → 2 rolls. Add 1 roll for complex roofs. Use breathable membrane for cold roofs.'],
      ['Fixings and accessories', 'Nails: tile nails (~2 per tile), batten nails (~1 per batten intersection). Screws: for metal roofing, ~8/m². Dry ridge kit: 1 kit per 10m ridge. Ventilation: 1 tile vent per 5-10 m² of roof space (check Part F).'],
    ],
    formulas: [
      ['Tiles', 'tiles = area × tiles_per_m² × (1 + waste%)'],
      ['Battens (linear m)', 'battens = area ÷ batten_gauge × 1.1'],
      ['Membrane (rolls)', 'rolls = ceil(area ÷ 60)'],
      ['Ridge tiles', 'ridge = ridge_length ÷ 0.4'],
    ],
    faqs: [
      ['What is a roofing takeoff?', 'A complete list of all materials needed: tiles, battens, membrane, nails, flashing, ridge, vents. Everything required to build the roof, quantified from the roof dimensions and pitch.'],
      ['How do I calculate battens for a roof?', 'roof_area ÷ batten_gauge × 1.1 (10% waste). At 35° with 345mm gauge: 100 m² ÷ 0.345 × 1.1 = 319 linear metres of batten.'],
      ['How many rolls of membrane do I need?', 'Roll coverage: ~60 m² effective (75 m² roll minus 150mm laps). 100 m² roof: 2 rolls. Add 1 for complex roofs.'],
      ['Best free roofing takeoff calculator?', 'One that covers tiles, battens, membrane, fixings, and flashing in one pass. This tool does all, free.'],
    ],
  },
  {
    slug: 'free-roofing-quote-calculator',
    defaultTab: 'smart-component',
    name: 'Roofing Quote Calculator',
    mTitle: 'Free Roofing Quote Calculator - Price Jobs Accurately | QuoteCore+',
    mDesc: 'Free roofing quote calculator. Price roofing jobs from materials, labour, waste, and overhead. Includes margin and tax. No signup required.',
    ogTitle: 'Free Roofing Quote Calculator - Price Jobs',
    ogDesc: 'Free roofing quote calculator. Price jobs accurately.',
    h1: 'Roofing Quote Calculator',
    hero: 'Price roofing jobs from material quantities, labour rates, waste, and overhead. Get a professional quote with margin and tax included. Free, no signup.',
    tipsH: 'Roofing quoting - did you know?',
    tips: [
      ['The quoting formula', 'Quote = (materials × 1.waste) + labour + overhead + margin. Materials at trade price (not retail). Labour: day rate × days. Overhead: 15-25% of (materials + labour). Margin: 15-30% on top. VAT/tax on the total.'],
      ['Material markup vs trade price', 'Roofers typically buy at 20-40% below retail. Quote materials at retail or slight discount (10% off retail shows customer they are getting a deal). Never quote at trade price - that gives away your buying advantage.'],
      ['Labour calculation', 'Labour = crew_size × day_rate × days. 3-man crew at £350/day each = £1,050/day. 100 m² concrete tile roof: ~3-4 days stripping and re-roofing. Labour: £3,150-4,200. Scaffold + skip on top.'],
      ['Common quoting mistakes', 'Forgetting scaffold (£500-1,500), underestimating waste, not pricing flashing/ridge/vents separately, no provision for timber repairs (rot found during strip). Always add a 10% contingency line.'],
    ],
    formulas: [
      ['Quote total', 'quote = (materials + labour + overhead) × (1 + margin%) × (1 + tax%)'],
      ['Materials with waste', 'materials = base_materials × (1 + waste%)'],
      ['Labour', 'labour = crew × day_rate × days'],
      ['Overhead', 'overhead = (materials + labour) × 20%'],
    ],
    faqs: [
      ['How do I price a roofing job?', '(materials × 1.waste + labour + overhead) × (1 + margin) × (1 + VAT). 100 m² concrete re-roof: materials £3k, labour £4k, overhead £1.4k, 20% margin, 20% VAT = ~£12.8k quote.'],
      ['What margin should I add to a roofing quote?', '15-30% is typical. 15% for competitive work, 20% standard, 25-30% for specialist work or small jobs (overhead is proportionally higher on small jobs).'],
      ['What overhead percentage for roofing?', '15-25% of (materials + labour). Covers insurance, vehicle, phone, office, advertising. Sole traders: 15%. Companies with premises/staff: 25%.'],
      ['Best free roofing quote calculator?', 'One that handles materials, labour, overhead, margin, and tax. This tool does all, free - and you can import quantities from the takeoff tab.'],
    ],
  },
];
